#lang racket
(define tolerance 0.00001)
(define (fixed-point f first-guess)
  (define (close-enough? v1 v2)
    (< (abs (- v1 v2)) tolerance))
  (define (try guess)
    (let ((next (f guess)))
      (display next)
      (newline)
      (if (close-enough? guess next)
          next
          (try next))))
  (try first-guess))

;(fixed-point (lambda (y) (+ 1 (/ 1 y))) 1.0)
(define (f x)
  (/ (log 1000) (log x)))
(define (f2 x)
  (/ (+ x (/ (log 1000) (log x))) 2))
(fixed-point f 2.0)
(fixed-point f2 2.0)